name: top-eleven
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pyyaml
  - tqdm
  - pytorch
  - pytorch-cuda=12.1
  - pytest
  - ipykernel
  - pip:
      - statsbombpy==1.18.0

